name: MLOps Pipeline

# We want to run it whenever the code is sent to 'main' branch
on:
  push:
    branches: [ "main" ]

# What job needs to be done
jobs:
  build-and-test:
    # INDENTATION FIX: These lines must be inside 'build-and-test'
    runs-on: ubuntu-latest

    steps:
    # Step A: Download your code onto the server
    - uses: actions/checkout@v3

    # Step B: Install Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    # Step C: Install the tools
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    # Step D: Run the test
    - name: Run Tests
      run: |
        pytest